force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Object to store employee details.</description>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Field to store employee&apos;s email.</description>
    <inlineHelpText>Field to store employee&apos;s email.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Field to store employee&apos;s first name.</description>
    <inlineHelpText>Field to store employee&apos;s first name.</inlineHelpText>
    <label>First Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Field to store employee&apos;s last name.</description>
    <inlineHelpText>Field to store employee&apos;s last name.</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to store employee&apos;s reporting manager.</description>
    <inlineHelpText>Field to store employee&apos;s reporting manager.</inlineHelpText>
    <label>Manager</label>
    <referenceTo>Manager__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to store assigned resource&apos;s Id.</description>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manager__c/Manager__c.object-meta.xml
<CustomObject>
    <description>Object to store manager details.</description>
    <label>Manager</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manager__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Field to store manager&apos;s email.</description>
    <inlineHelpText>Field to store manager&apos;s email.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Manager__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Field to store manager&apos;s first name.</description>
    <inlineHelpText>Field to store manager&apos;s first name.</inlineHelpText>
    <label>First Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Manager__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Field to store manager&apos;s last name.</description>
    <inlineHelpText>Field to store manager&apos;s last name.</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <description>Object to store resource details.</description>
    <label>Resource</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/employee/tests/Test_Employee.cls
/**
 * @description Test class for Employee.cls
 */
@isTest
public class Test_Employee {

    /**
     * @description Test data setup
     */
    @TestSetup
    static void setupData(){
        Test_Employee_Factory factory = new Test_Employee_Factory();
        factory.insertEmployee();
        factory.createEmployeeWithManagerAndResource();
    }

    /**
     * @description givenEmployee_WhenInserted_ThenUserShouldBeCreated
     * GIVEN: Employee record
     * WHEN: Inserted
     * THEN: User should be created for the employee
     */
    @isTest
    public static void givenEmployee_WhenInserted_ThenUserShouldBeCreated() {
        // ARRANGE: Query created employee
        Employee__c employee = [SELECT Id, First_Name__c, Last_Name__c, Email__c FROM Employee__c WHERE First_Name__c = 'insertEmployee' WITH SECURITY_ENFORCED];

        // ARRANGE: Query user record
        User user = [SELECT Id, Email, FirstName, LastName FROM User WHERE FirstName = :employee.First_Name__c AND Email = :employee.Email__c WITH SECURITY_ENFORCED];

        // ASSERT: Ensure user record is created for the employee
        System.assertNotEquals(null, user, 'User should be created for the employee.');
        System.assertEquals(employee.First_Name__c, user.FirstName, 'First names should match.');
        System.assertEquals(employee.Last_Name__c, user.LastName, 'Last names should match.');
        System.assertEquals(employee.Email__c, user.Email, 'Email addresses should match.');
    }

    /**
     * @description givenEmployee_WhenUnauthorizedUserAssignsResource_ThenErrorShouldBeThrown
     * GIVEN: Employee record
     * WHEN: Unauthorized user assigns resource to an employee
     * THEN: Validation error should be thrown
     */
    @isTest
    public static void givenEmployee_WhenUnauthorizedUserAssignsResource_ThenErrorShouldBeThrown() {
        
        //ARRANGE: Setup error message string
        String errorMsg = 'You are unauthorized to assign resource to this employee.';

        // ARRANGE: Query created employee
        Employee__c employee = [SELECT Id, First_Name__c, Last_Name__c, Email__c, Resource__c, Manager__c FROM Employee__c WHERE First_Name__c = 'createEmployeeWithManagerAndResource'];

        // ARRANGE: Query content document
        Resource__c resource = [SELECT Id FROM Resource__c WHERE Name = 'createEmployeeWithManagerAndResource'];

        Test.startTest();
        try {
            employee.Resource__c = resource.Id;
            update employee;
        } catch (DmlException e) {
            System.assertEquals(true, e != null, 'Error should not be null.');
        }
        Test.stopTest();
    }
}