force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Object to store employee details.</description>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to store employee&apos;s reporting manager.</description>
    <inlineHelpText>Field to store employee&apos;s reporting manager.</inlineHelpText>
    <label>Manager</label>
    <referenceTo>Manager__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to store assigned resource&apos;s Id.</description>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manager__c/Manager__c.object-meta.xml
<CustomObject>
    <description>Object to store manager details.</description>
    <label>Manager</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <description>Object to store resource details.</description>
    <label>Resource</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Resource__c/Training_Resource__c.object-meta.xml
<CustomObject>
    <description>Junction object to create many to many relationship between employees and resources.</description>
    <label>Training Resource</label>
    <nameField>
        <displayFormat>TRS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Resource__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Training Resources</relationshipLabel>
    <relationshipName>Training_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Resource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Training Resources</relationshipLabel>
    <relationshipName>Training_Resources</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/homepageController/HomepageController.cls
/**
 * @description Class for operations related to the home page.
 */
public with sharing class HomepageController {

    /**
     * @description Method to return list of training resources or employees based on current user
     * @return list of sobjects
     */
    @AuraEnabled(cacheable=true)
    public static List<SObject> fetchList() {
        List<SObject> response = new List<SObject>();
        Id currentUserId = UserInfo.getUserId();

        List<SObject> userRoles = [SELECT Id, (SELECT Id FROM Manager__r), (SELECT Id FROM Employee__r) FROM User WHERE Id =: currentUserId];

        if (!userRoles.isEmpty()) {
            SObject userRole = userRoles[0];
            if (!userRole.getSObjects('Manager__r').isEmpty()) {
                response = (List<SObject>) fetchEmployees(userRole.getSObjects('Manager__r')[0].Id);
            } else if (!userRole.getSObjects('Employee__r').isEmpty()) {
                response = (List<SObject>) fetchTrainingResources(userRole.getSObjects('Employee__r')[0].Id);
            }
        }
        return response;
    }

    /**
     * @description Method to return list of training resources assigned to an employee
     * @param userId holds employee's Id
     * @return list of training resources
     */
    public static List<Training_Resource__c> fetchTrainingResources(Id userId){
        try {
            return [SELECT Id, Employee__c, Resource__c, Resource__r.Name FROM Training_Resource__c WHERE Employee__c =: userId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    /**
     * @description Method to return list of employees under the specified manager
     * @param userId holds manager's Id
     * @return list of employees
     */
    public static List<Employee__c> fetchEmployees(Id userId){
        try {
            return [SELECT Id, Name, Manager__c FROM Employee__c WHERE Manager__c =: userId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}