force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Object to store employee details.</description>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Field to store employee&apos;s email.</description>
    <inlineHelpText>Field to store employee&apos;s email.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to store employee&apos;s reporting manager.</description>
    <inlineHelpText>Field to store employee&apos;s reporting manager.</inlineHelpText>
    <label>Manager</label>
    <referenceTo>Manager__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Manager__c/Manager__c.object-meta.xml
<CustomObject>
    <description>Object to store manager details.</description>
    <label>Manager</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manager__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Field to store manager&apos;s email.</description>
    <inlineHelpText>Field to store manager&apos;s email.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Manager__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/user/User.cls
/**
 * @description Class for operations related to the user object
 */
public with sharing class User {
    /**
     * @description Method to update entity's user id field
     */
    public static void updateEntityUserId (List<Schema.User> users) {
        Map<String, Id> emailToUserIdMap = new Map<String, Id>();

        for (Schema.User user : users) {
            emailToUserIdMap.put(user.Email, user.Id);
        }

        List<Employee__c> employees = [
            SELECT Id, User_Id__c, Email__c 
            FROM Employee__c 
            WHERE Email__c IN :emailToUserIdMap.keySet()
        ];

        List<Manager__c> managers = [
            SELECT Id, User_Id__c, Email__c 
            FROM Manager__c 
            WHERE Email__c IN :emailToUserIdMap.keySet()
        ];

        if(employees.size() > 0) {
            for (Employee__c employee : employees) {
                if (emailToUserIdMap.containsKey(employee.Email__c)) {
                    employee.User_Id__c = emailToUserIdMap.get(employee.Email__c);
                }
            }
            update employees;
        }

        if(managers.size() > 0) {
            for (Manager__c manager : managers) {
                if (emailToUserIdMap.containsKey(manager.Email__c)) {
                    manager.User_Id__c = emailToUserIdMap.get(manager.Email__c);
                }
            }
            update managers;
        }
    }
}