force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Object to store employee details.</description>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field to store assigned resource&apos;s Id.</description>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <description>Object to store resource details.</description>
    <label>Resource</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Resource__c/Training_Resource__c.object-meta.xml
<CustomObject>
    <description>Junction object to create many to many relationship between employees and resources.</description>
    <label>Training Resource</label>
    <nameField>
        <displayFormat>TRS-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Training Resources</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Training_Resource__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Training Resources</relationshipLabel>
    <relationshipName>Training_Resources</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training_Resource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <label>Resource</label>
    <referenceTo>Resource__c</referenceTo>
    <relationshipLabel>Training Resources</relationshipLabel>
    <relationshipName>Training_Resources</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/trainingResource/TrainingResource.cls
/**
 * @description Class for operations related to Training Resource object.
 */
public with sharing class TrainingResource {
    /**
     * @description Method for creating training resource records to assign resources to employees
     * @param employeeId holds employee's Id
     * @param resourceIds holds list of resource Ids
     */
    @AuraEnabled
    public static void assignResources(String employeeId, List<Id> resourceIds){
        try {
            Set<Id> assignedResources = new Set<Id>();
            for(Training_Resource__c rsc : [SELECT Id, Employee__c, Resource__c FROM Training_Resource__c WHERE Employee__c =: employeeId]) {
                assignedResources.add(rsc.Resource__c);
            }

            List<Training_Resource__c> trainingResources = new List<Training_Resource__c>();
            for(String rscId : resourceIds) {
                if(!assignedResources.contains(rscId)) {
                    trainingResources.add(new Training_Resource__c(
                        Employee__c = employeeId,
                        Resource__c = rscId
                    ));
                }
            }
            if(!trainingResources.isEmpty()) {
                insert trainingResources;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}