force-app/main/default/objects/Manager__c/Manager__c.object-meta.xml
<CustomObject>
    <description>Object to store manager details.</description>
    <label>Manager</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manager__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Field to store manager&apos;s email.</description>
    <inlineHelpText>Field to store manager&apos;s email.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Manager__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Field to store manager&apos;s first name.</description>
    <inlineHelpText>Field to store manager&apos;s first name.</inlineHelpText>
    <label>First Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Manager__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Field to store manager&apos;s last name.</description>
    <inlineHelpText>Field to store manager&apos;s last name.</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/manager/Manager.cls
/**
 * @description Class for operations related to the manager object
 */
public with sharing class Manager {
    public static void createUsersForManagers (List<Manager__c> managers) {
        
        List<User> users = new List<User>();
        Id profileId = [SELECT Id FROM Profile WHERE Name = 'Standard Platform User' WITH SECURITY_ENFORCED].Id;
        
        for(Manager__c manager : managers) {
            users.add(new User(
                Username = manager.Email__c,
                Email = manager.Email__c,
                FirstName = manager.First_Name__c,
                LastName = manager.Last_Name__c,
                Alias = manager.First_Name__c,
                CommunityNickname = 'PlatformUser',
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                ProfileId = profileId
            ));
        }

        insert users;
    }
}