force-app/main/default/objects/Manager__c/Manager__c.object-meta.xml
<CustomObject>
    <description>Object to store manager details.</description>
    <label>Manager</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manager__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Field to store manager&apos;s email.</description>
    <inlineHelpText>Field to store manager&apos;s email.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Manager__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Field to store manager&apos;s first name.</description>
    <inlineHelpText>Field to store manager&apos;s first name.</inlineHelpText>
    <label>First Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Manager__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Field to store manager&apos;s last name.</description>
    <inlineHelpText>Field to store manager&apos;s last name.</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/employee/tests/factory/Test_Manager_Factory.cls
/**
 * @description Factory class for Manager
 */
@isTest
public class Test_Manager_Factory {

    /**
     * @description Method to insert manager record
     */
    public void insertManager() {
        Manager__c manager = new Manager__c(
            First_Name__c = 'insertManager',
            Last_Name__c = '0',
            Email__c = 'inserManager@insertManager.com'
        );
        insert manager;
    }
}