force-app/main/default/objects/Manager__c/Manager__c.object-meta.xml
<CustomObject>
    <description>Object to store manager details.</description>
    <label>Manager</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manager__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Field to store manager&apos;s first name.</description>
    <inlineHelpText>Field to store manager&apos;s first name.</inlineHelpText>
    <label>First Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Manager__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Field to store manager&apos;s last name.</description>
    <inlineHelpText>Field to store manager&apos;s last name.</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/employee/tests/Test_Manager.cls
/**
 * @description Test class for Manager.cls
 */
@isTest
public class Test_Manager {

    /**
     * @description Test data setup
     */
    @TestSetup
    static void setupData(){
        Test_Manager_Factory factory = new Test_Manager_Factory();
        factory.insertManager();
    }

    /**
     * @description givenManager_WhenInserted_ThenUserShouldBeCreated
     * GIVEN: Manager record
     * WHEN: Inserted
     * THEN: User should be created for the manager
     */
    @isTest
    public static void givenManager_WhenInserted_ThenUserShouldBeCreated() {
        // ARRANGE: Query created manager
        Manager__c manager = [SELECT Id, First_Name__c, Last_Name__c FROM Manager__c WHERE First_Name__c = 'insertManager' WITH SECURITY_ENFORCED];

        // ARRANGE: Query user record
        Schema.User user = [SELECT Id, Email, FirstName, LastName FROM User WHERE FirstName = :manager.First_Name__c WITH SECURITY_ENFORCED];

        // ASSERT: Ensure user record is created for the manager
        System.assertNotEquals(null, user, 'User should be created for the manager.');
        System.assertEquals(manager.First_Name__c, user.FirstName, 'First names should match.');
        System.assertEquals(manager.Last_Name__c, user.LastName, 'Last names should match.');
    }
}