force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <description>Object to store resource details.</description>
    <label>Resource</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Content_Id__c.field-meta.xml
<CustomField>
    <fullName>Content_Id__c</fullName>
    <description>Field to store linked Content Document&apos;s Id for internal usage.</description>
    <label>Content Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resource__c/fields/File_Linked__c.field-meta.xml
<CustomField>
    <fullName>File_Linked__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to identify if file is linked.</description>
    <label>File Linked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/resource/Resource.cls
/**
 * @description Class for operations related to resource object.
 */
public with sharing class Resource {

    // Constants
    public static String OBJECT_API_NAME = 'Resource__c';

    /**
     * @description Method to commit file upload changes on resource record.
     */
    @AuraEnabled
    public static void commitUploadChanges(Id recordId, String contentId) {
        try {
            Resource__c rsc = [SELECT Id, Content_Id__c, File_Linked__c FROM Resource__c WHERE Id =: recordId WITH SECURITY_ENFORCED];
            rsc.Content_Id__c = contentId;
            rsc.File_Linked__c = true;
            update rsc;
        } catch (Exception e) {
            throw new AuraHandledException('Error: ' + e.getMessage());
        }
    }

    /**
     * @description Method to fetch content Id associated with the resource.
     */
    @AuraEnabled
    public static string fetchContentId(Id recordId){
        try {
            return [SELECT Id, Content_Id__c FROM Resource__c WHERE Id =: recordId WITH SECURITY_ENFORCED].Content_Id__c;
        } catch (Exception e) {
            throw new AuraHandledException('Error: ' + e.getMessage());
        }
    }
}