force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>Object to store department details.</description>
    <label>Department</label>
    <nameField>
        <displayFormat>DEP-{00000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Object to store employee details.</description>
    <label>Employee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Field to store employee&apos;s department.</description>
    <inlineHelpText>Field to store employee&apos;s department.</inlineHelpText>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Field to store employee&apos;s email.</description>
    <inlineHelpText>Field to store employee&apos;s email.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Field to store employee&apos;s first name.</description>
    <inlineHelpText>Field to store employee&apos;s first name.</inlineHelpText>
    <label>First Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Field to store employee&apos;s last name.</description>
    <inlineHelpText>Field to store employee&apos;s last name.</inlineHelpText>
    <label>Last Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Field to store employee&apos;s role.</description>
    <inlineHelpText>Field to store employee&apos;s role.</inlineHelpText>
    <label>Role</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intern</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/employee/tests/factory/Test_Employee_Factory.cls
/**
 * @description Factory class for Employee
 */
@isTest
public class Test_Employee_Factory {

    /**
     * @description Method to insert employee record
     */
    public void insertEmployee() {

        Department__c department = new Department__c(
            Name = 'insertEmployee'
        );
        insert department;

        Employee__c employee = new Employee__c(
            First_Name__c = 'insertEmployee',
            Last_Name__c = '0',
            Email__c = 'insertEmployee@employee.com',
            Department__c = department.Id,
            Role__c = 'Intern'
        );
        insert employee;
    }
}