force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <description>Object to store department details.</description>
    <label>Department</label>
    <nameField>
        <displayFormat>DEP-{00000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/Resource__c.object-meta.xml
<CustomObject>
    <description>Object to store resource details.</description>
    <label>Resource</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resource__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Field to determine Resource&apos;s role scope.</description>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Roles</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Roles.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Intern</fullName>
    </customValue>
    <customValue>
        <fullName>QA Intern</fullName>
    </customValue>
    <customValue>
        <fullName>QA Lead</fullName>
    </customValue>
    <customValue>
        <fullName>QA Trainee</fullName>
    </customValue>
    <customValue>
        <fullName>Quality Analyst</fullName>
    </customValue>
    <customValue>
        <fullName>Senior Software Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Software Engineer</fullName>
    </customValue>
    <customValue>
        <fullName>Team Lead</fullName>
    </customValue>
    <customValue>
        <fullName>Trainee</fullName>
    </customValue>
    <description>Global picklist value set for Employee roles.</description>
    <masterLabel>Roles</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/resource/ResourceController.cls
/**
 * @description Controller class for resource related operations
 */
public with sharing class ResourceController {
    /**
     * @description Method to fetch resources based on employee's department
     * @param department holds employee's department
     * @param role holds employee's role
     * @return Map<String, List<Resource__c>> where string is the role identifier
     */
    @AuraEnabled
    public static Map<String, List<Resource__c>> fetchResources(String department, String role){
        try {
            Map<String, List<Resource__c>> response = new Map<String, List<Resource__c>>();
            List<Resource__c> roleSpecifiedResources = new List<Resource__c>();
            List<Resource__c> generalResources = new List<Resource__c>();
            
            List<Resource__c> resources = [SELECT Id, Name, Role__c FROM Resource__c WHERE Department__c =: department];
            for(Resource__c resource : resources) {
                if(resource.Role__c == role){
                    roleSpecifiedResources.add(resource);
                } else if(String.isEmpty(resource.Role__c)){
                    generalResources.add(resource);
                }
            }
            if(roleSpecifiedResources.size() > 0 || generalResources.size() > 0){
                response = new Map<String, List<Resource__c>>{
                    'roleSpecified' => roleSpecifiedResources,
                    'general' => generalResources
                };
            }
            return response;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}